spring:
  jpa:
    properties:
      jdbc:
        batch_size: 500
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_URL}
  jackson:
    default-property-inclusion: NON_NULL
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  
etterna:
  note-info-folder-path: ${NOTE_INFO_FOLDER_PATH}
  multi-base-url: ${MULTI_API_URL}
  calc:
    scheduler:
      enabled: ${CALC_SCHEDULER_ENABLED}

opensearch:
  ssl:
    enabled: ${OPENSEARCH_SSL_ENABLED}
  db:
    host: ${OPENSEARCH_HOST}
    port: ${OPENSEARCH_PORT}
    username: ${OPENSEARCH_USER}
    password: ${OPENSEARCH_PASS}

server:
  port: ${SOCKET_PORT}
  ssl:
    key-alias: ${SSL_ALIAS}
    key-store: ${SSL_KEYSTORE}
    key-store-password: ${SSL_KEYSTORE_PASS}
    key-password: ${SSL_PASSWORD}
    

logging:
  level:
    #org.hibernate.SQL: DEBUG
    com.etterna: DEBUG